### ISSUE TITLE
Support more file systems for SD cards ("SD card corrupted" notification on AOSP ROMs)

### ISSUE THREAD

**Issue by Uzurka** [TenSeventy7/android_kernel_samsung_exynos9610_fresh#12]
Corrupted SD CARD with mint kernel.
Format via the smartphone don't make it usable, the card work perfectly in TWRP or attached to a computer. 
Issue only with this kernel with a SM-A505FN with LineageOS 18.1 and PixelOS

**Comment by TenSeventy7** [comment]
Completed with Mint 12.2.
