### ISSUE TITLE
please provide support for samsung m31 device it is similar to a50s . Please and is there ant ims implementation to make volte work on custom roms

### ISSUE THREAD

**Issue by AMIRTHESWARAN** [TenSeventy7/android_kernel_samsung_exynos9610_fresh#16]
The platform is similar to m31 and the device features too. Please provide support for mint kernel and fresh rom for samsung m31. Also please joint the m31 development telegram   https://t.me/galaxym31development   
there are many people waiting for you kernel and rom.

**Comment by TenSeventy7** [comment]
I have no plans supporting other Samsung devices right now, sorry.
