### ISSUE TITLE
[Galaxy A50] Says missing Firmware but Firmware there

### ISSUE THREAD

**Issue by AnaxMorden** [TenSeventy7/android_kernel_samsung_exynos9610_fresh#2]
I currency habe this confusing error that i cant solve ( See errors )
I already googled it ( Used Google as Web Engine ) but it found nothing.
I also added the Firmware path and Firmware Name to the Defconfig like the link under the Text but this didnt helped at all. After compiling I got the same error again

### Tried Solution

[ Fix for Defconfig ](https://github.com/hgunduz295/androidd_kernel_samsung_universal9610/commit/92eda8d4cce42cc88d8688581a586eb0f919e5be#diff-725dee1b5969e869d347d824338588038e684a18c72a5e7afd1fe76c296618ec) Didn`t worked

### Errors
` firmware/tsp_imagis/ist40xx_a80.bin.gen.S: Assembler messages:
firmware/tsp_imagis/ist40xx_a80.bin.gen.S:5: Error: file not found: firmware/tsp_imagis/ist40xx_a80.bin `

### Log
[click here ](https://pastebin.com/kdvPmZAq)
( error is in line 988 )

( Sry if i'm having an bad english )

( used upstream kernel ) 

### Attached Things
I put down the defconfig file, my applied patches and the APKBUILDS file for more info if needed
 

* [APKBUILD ](https://github.com/TenSeventy7/android_kernel_samsung_exynos9610_fresh/files/6630821/APKBUILD.txt) ( includes Download way, used comment id, flags and more )
* [Defconfig](https://github.com/TenSeventy7/android_kernel_samsung_exynos9610_fresh/files/6630830/config-samsung-a505fn.aarch64.txt)
*  [No Magisk Patch](https://github.com/TenSeventy7/android_kernel_samsung_exynos9610_fresh/files/6630832/no_magisk.patch.txt)

I hope you can fix this patch

**Comment by TenSeventy7** [comment]
**Have you tried using a different cross-compiler?**

You also don't need to remove Magisk this way, just define these on the defconfig:
`CONFIG_INITRAMFS_SOURCE=""
CONFIG_INITRAMFS_SKIP=y# CONFIG_INITRAMFS_FORCE is not set# CONFIG_INITRAMFS_COMPRESSION_GZIP is not set# CONFIG_INITRAMFS_COMPRESSION_BZIP2 is not set# CONFIG_INITRAMFS_COMPRESSION_LZMA is not set# CONFIG_INITRAMFS_COMPRESSION_XZ is not set# CONFIG_INITRAMFS_COMPRESSION_LZO is not set# CONFIG_INITRAMFS_COMPRESSION_LZ4 is not set`

**Comment by AnaxMorden** [comment]
ok i'll try it out to compile it with the script that is in the kernel source

**Comment by AnaxMorden** [comment]
now it says:

make[2]: *** No rule to make target 'firmware/tsp_imagis/ist40xfirmware/tsp_imagis/ist40xx_a80.bin', needed by 'firmware/tsp_imagis/ist40xfirmware/tsp_imagis/ist40xx_a80.bin.gen.o'.  Stop.
make[2]: *** Waiting for unfinished jobs....
  MK_FW   firmware/tsp_imagis/ist40xfirmware/tsp_imagis/ist40xx_a80.bin.gen.S
make[1]: *** [/home/pmos/build/src/android_kernel_samsung_exynos9610_fresh-ecb51ba3a506ab54c9916f89c955afc5e0f21bca/Makefile:1236: firmware] Error 2
make[1]: *** Waiting for unfinished jobs....

[Log Here](https://pastebin.com/MbA6JaBd)
( Error at Line 824 )

**Comment by TenSeventy7** [comment]
**Try reverting the patch.** The defined path on the defconfig is incorrect anyway.

`CONFIG_EXTRA_FIRMWARE="tsp_imagis/ist40xfirmware/tsp_imagis/ist40xx_a80.bin"` should be `CONFIG_EXTRA_FIRMWARE="tsp_imagis/ist40xx_a80.bin"`

By the looks of it, the GCC compiler included with Alpine Linux doesn't properly parse `CONFIG_EXTRA_FIRMWARE`.

Also try a different GCC build instead. I'm having trouble getting Clang-compiled kernels to boot.

**Comment by AnaxMorden** [comment]
Thats good to now
And yeah i fix this

**Comment by AnaxMorden** [comment]
It is the same error like above in Clang
But I think what the error is:
It says:
 firmware/tsp_imagis/ist40xx_a80.bin.gen.S:5: Error: file not found: firmware/tsp_imagis/ist40xx_a80.bin 

That means it searches in the same folder where ist40xx_a80.bin.gen.S is and so there cant be firmware/tsp_imagis/ist40xx_a80.bin because the script is in firmware/tsp_imagis
and it does not redirect to the kernel root folder 
( hope it is understandable ) 
I'll try it to fix this with a patch somehow

**Comment by AnaxMorden** [comment]
I found an interesting error / not / warning ( i dont know it does not say this ) that says:
../firmware/Makefile:79: target 'firmware/tsp_imagis/ist40xx_a80.bin.gen.S' given more than once in the same rule

( Log above )
At Line 1076

Could this be the main issue?

**Comment by AnaxMorden** [comment]
Not needed amymore
