### ISSUE TITLE
Add to kernel Mint Magisk Delta 

### ISSUE THREAD

**Issue by captry** [TenSeventy7/android_kernel_samsung_exynos9610_fresh#21]
stock Magisk doesn't pass the test of payment soft

**Comment by captry** [comment]
stock Magisk doesn't pass the test of payment soft

**Comment by rushiranpise** [comment]
it wont pass with delta either.
you need play integrity fix or usnf module in order to pass


Here are alpha/delta/lite
https://github.com/rushizgithub/android_kernel_samsung_exynos9610_mint/releases

**Comment by mistrmochov** [comment]
Here is the kernel with latest magisk delta(kitsune mask) https://github.com/dvoracekma2019/galaxya50_mintkernel_magiskdelta/releases/tag/1378_R656426A5-kitsune
