### ISSUE TITLE
Is there specific reason for only Android 11 and 12 releases ?

### ISSUE THREAD

**Issue by Latruffy** [TenSeventy7/android_kernel_samsung_exynos9610_fresh#26]
Hello,
not really an issue but more a question to clearly understand, but I found nowhere else to ask : 
I'm owning an A505FN, installed [TWRP 3.7.0](https://github.com/GiovanYCringe/device_samsung_a505f/releases), and wish to install a [LineageOS 21.0](https://sourceforge.net/projects/andyyan-gsi/files/lineage-21-td/lineage-21.0-20241118-UNOFFICIAL-arm64_bgN-signed.img.gz/download), with Magisk 27.0 at least.
I'm going to download and use the asset MintBeta-1388.A12.AOSP-Enforcing-Magisk_A50.CI.zip.
Since LinageOS 21.0 is gased on Android 14.0, I would have prefered a MintBeta release A14, but can't find.
Then my question "Is there specific reason for only Android 11 and 12 releases ?"

BTW, I choose AOSP since I'm trying to install a custom ROM. Should I select OneUI (3 or 4 ?) instead, considering only the device which is a Samsung Galaxy one ?

Thanks by advance for your answers.

**Comment by TenSeventy7** [comment]
Android 12 kernels are for Android 12 **and later.**
