### ISSUE TITLE
Magisk Alpha kernel for OneUI 3.1 A11

### ISSUE THREAD

**Issue by maej72** [TenSeventy7/android_kernel_samsung_exynos9610_fresh#27]
I tried to patch this kernel with the Magisk alpha manager, but I got a bootloop.

Can you please provide a ready-made version or a tutorial on integrating the latest Magisk into the kernel?

Thank you.

**Comment by PeterKnecht93** [comment]
Implemented on https://github.com/FreshROMs/android_kernel_samsung_exynos9610_mint/commit/41f7beaacf86d4397f55530b7eefcf9720b3433f, check out the latest Beta build.
