### ISSUE TITLE
[QUESTION][NON-ONEUI] Does this kernel works and is stable on non-oneui roms (aosp based)?

### ISSUE THREAD

**Issue by ghost** [TenSeventy7/android_kernel_samsung_exynos9610_fresh#4]
The title is pretty clear, was browsing XDA forums until I find this amazing kernel, so I decided to upgrade to android R (11) before flashing since its advised todo so.

The thing now is that I want to try a non-oneui rom ([this dotos project](https://forum.xda-developers.com/t/rom-11-0-beta-dotos-v5-2-1-aosp-2022-01-02.4382401/)), and I'm asking if it works before trying to flash.

**Comment by TenSeventy7** [comment]
A separate variant of the kernel is available for non-One UI/AOSP ROMs. :>

**Comment by ghost** [comment]
Thanks.
