### ISSUE TITLE
"mainline-15" causes bootloop on AOSP

### ISSUE THREAD

**Issue by ghost** [TenSeventy7/android_kernel_samsung_exynos9610_fresh#6]
Salutations, as the title suggest, flashing the latest and greatest release "mainline-15" causes a bootloop on my device, but the older releases work fine.

### My phone specifications:
- Device model: `SM-A505F`
- Baseband version: `A505FXXS9CUL1`
- Current rom: LineageOS Stable 18.1 (Unofficial).
- Recovery: SHRP-stable-3.1 (Unofficial).

Note: The phone is unusable after flashing the kernel and rebooting to the recovery, even pressing the vol-up button do not make any effects, the only way out is to enter download mode and flash the stock rom.

**Comment by TenSeventy7** [comment]
Please provide logs.

**Comment by ghost** [comment]
UPDATE: Weirdly enough, after flashing the stock ROM (I bricked my phone.), and then reflashing everything as usual, the kernel works fine, zygisk and everything, weird...

Well, sorry if I disturbed you or any contributors.

Cordially.
