### ISSUE TITLE
Sensor changes on Feb 2022 update (Accelerometer not working)

### ISSUE THREAD

**Issue by FarahJafrinFJ** [TenSeventy7/android_kernel_samsung_exynos9610_fresh#8]
Hey there,
My device is Galaxy A50 (A505F/DS) (a50dd). After installing the Magisk 24.3 rooted kernel Mint Beta (beta-613), My screen rotation is not working. I've tested that it's causing after flashing the kernel. I've done doing full stock firmware flash and after that my screen rotation works. But after flashing the kernel, screen rotation doesn't work.

**Comment by TenSeventy7** [comment]
Please provide screenshots of a sensor testing app showing accelerometer data, a screenshot of Settings > About device > Software information, **and logs.**

**Comment by FarahJafrinFJ** [comment]
> Please provide screenshots of a sensor testing app showing accelerometer data, a screenshot of Settings > About device > Software information, **and logs.**

**Here is the screenshots.**

**Software information**
![Screenshot_20220315-182452_Settings.jpg](https://user-images.githubusercontent.com/75559397/158379281-04fd372e-acdc-448b-a42f-3ac07c188578.jpg)

**Accelerometer data**
![Screenshot_20220315-182238_Test Your Android.jpg](https://user-images.githubusercontent.com/75559397/158379502-c9285c7d-5545-4beb-870d-293df174b66c.jpg)
![Screenshot_20220315-182211_Test Your Android.jpg](https://user-images.githubusercontent.com/75559397/158379524-1ee70010-e269-470a-b93d-d1f2990934bf.jpg)
![Screenshot_20220315-182203_Test Your Android.jpg](https://user-images.githubusercontent.com/75559397/158379547-85889d6f-edbd-40f4-810e-39e4d464af1c.jpg)
![Screenshot_20220315-182147_Test Your Android.jpg](https://user-images.githubusercontent.com/75559397/158379566-f20556d6-9646-448e-ab3f-32eb56920ea9.jpg)

**Here is the logcat**
![logcat_03-15-2022_18-43-14.txt](https://github.com/FreshROMs/android_kernel_samsung_exynos9610_mint/files/8253381/logcat_03-15-2022_18-43-14.txt)

**Comment by TenSeventy7** [comment]
Confirmed. Samsung has changed the sensor drivers in the vendor and kernel starting CVB1.

I'm not sure how can I fix this without breaking those with older bootloaders but thanks for reporting.

**Comment by FarahJafrinFJ** [comment]
What should I do now for solving this problem for now until you find a fix? Should I downgrade my firmware? And thanks for helping 😊

**Comment by TenSeventy7** [comment]
> What should I do now for solving this problem for now until you find a fix? Should I downgrade my firmware? And thanks for helping 😊

A ROM with an older vendor should work (i.e. those with CVA3 and older).

**Comment by TenSeventy7** [comment]
Quick thing. Can you try this build and see if accelerometer (and pocket detection) now works for you?

[Uploading MintBeta-649_11_OneUI-Enforcing_A50_1647401036_CI.zip…]()

**Comment by TenSeventy7** [comment]
Quick thing. Can you try this build and check if the accelerometer (and pocket detection) now works for you?

[MintBeta-649_11_OneUI-Enforcing_A50_1647401036_CI.zip](https://drive.google.com/uc?export=download&id=1Glgnf-tUNYpyNaId-pMA6zZw8vWJHd4I)

**Comment by FarahJafrinFJ** [comment]
> Quick thing. Can you try this build and check if the accelerometer (and pocket detection) now works for you?
> 
> [MintBeta-649_11_OneUI-Enforcing_A50_1647401036_CI.zip](https://drive.google.com/uc?export=download&id=1Glgnf-tUNYpyNaId-pMA6zZw8vWJHd4I)

It's working, Thanks a lot!

**Comment by TenSeventy7** [comment]
> It's working, Thanks a lot!

Thanks for testing! Fixed on https://github.com/FreshROMs/android_kernel_samsung_exynos9610_mint/commit/7ee37c35bbdc9fd877fdf2ac5ba9a134c87c9a17.
